### ISSUE TITLE
Could not correctly encode receipts for header #15511259 0x3017b9e4d0bb214e90dc002c6a52bd7bd920fb1e2eddd1cf9687c702cd9dc72a

### ISSUE THREAD

**Issue by pipermerriam** [carver/eth-portal#32]
_If this is a bug report, please fill in the following sections.
If this is a feature request, delete and describe what you would like with examples._

## What was wrong?

Ran into this error while running the client.

### Full error output 

```sh
Traceback (most recent call last):
  File "/home/pipermerriam/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pipermerriam/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pipermerriam/projects/eth-portal/eth_portal/bridge/__main__.py", line 4, in <module>
    launch_bridge()
  File "/home/pipermerriam/projects/eth-portal/eth_portal/bridge/run.py", line 51, in launch_bridge
    header_log_loop(w3, portal_inserter, block_filter, 6)
  File "/home/pipermerriam/projects/eth-portal/eth_portal/bridge/run.py", line 34, in header_log_loop
    handle_new_header(w3, portal_inserter, header_hash)
  File "/home/pipermerriam/projects/eth-portal/eth_portal/bridge/handle.py", line 32, in handle_new_header
    propagate_receipts(w3, portal_inserter, chain_id, block_fields, transactions)
  File "/home/pipermerriam/projects/eth-portal/eth_portal/bridge/history.py", line 213, in propagate_receipts
    content_key, content_value = encode_receipts_content(
  File "/home/pipermerriam/projects/eth-portal/eth_portal/bridge/history.py", line 247, in encode_receipts_content
    raise ValidationError(
eth_utils.exceptions.ValidationError: Could not correctly encode receipts for header #15511259 0x3017b9e4d0bb214e90dc002c6a52bd7bd920fb1e2eddd1cf9687c702cd9dc72a
 
```

### Expected Result

_This section may be deleted if the expectation is "don't crash"._

The client not to crash.

## How can it be fixed?

I suspect we will want that validation error to include more information on the exact contents it was trying to encode....

**Comment by pipermerriam** [comment]
ran into this again:

```
eth_utils.exceptions.ValidationError: Could not correctly encode receipts for header #15527608 0xe0f97cadbb01f635f444f4e871ea83e267fb0ebadb130a4ca20c617cda252176
```

**Comment by carver** [comment]
The time I've seen this particular errors, there have been others before it (like a "could not find transaction" error). I assume you didn't notice a traceback that came before this one?

Totally 👍🏻 on offering more info here, somehow. The encoded content is sometimes quite large, but probably worth just spewing anyway, for now.

**Comment by pipermerriam** [comment]
> I assume you didn't notice a traceback that came before this one?

Correct.  This was a standalone traceback with nothing indicating prior problems.

> The encoded content is sometimes quite large, but probably worth just spewing anyway, for now.

Spew, or write to a temporary file somewhere and just give a file path...

**Comment by carver** [comment]
> write to a temporary file somewhere and just give a file path...

Went this route. Binary data for header #15511259 is 394KB. Spew would probably not have helped.
